# Site-wide settings


# Variables
title: tmcraft.us
description: >- 
  Personal webpage that contains my blog, contact information, and other various things.
url: "https://tmcraft.us"
collections_dir: _pages


# Site owner
owner:
  name: Tyler Hamrick
  email: hamrtw02@gmail.com
  bio: "Undergrad Student studying Informatics @ Indiana University Bloomington"

# Owner's socials
social:
  github: twhamr
  linkedin: tywahamr
  twitter:
  instagram:
  youtube:


# Build settings
theme: minima
plugins:
  - jekyll-feed

include: ['_pages']
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
