# Site settings
title: "Tyler Hamrick - Developer Portfolio"
email: hamrtw02@gmail.com
description: >-
  Full-stack developer passionate about creating innovative solutions
  and building meaningful projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tmcraft.us" # the base hostname & protocol for your site
twitter_username: realtylenol
github_username: twhamr
linkedin_username: tywahamr

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  experiences:
    output: false
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"