source "https://rubygems.org"

# Use GitHub Pages gem for compatibility
gem "github-pages", "~> 232", group: :jekyll_plugins

# Additional plugins
gem "jekyll-feed", "~> 0.15"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"

# Windows and JRuby specific gems
platforms :windows do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Performance booster for watching directories on Windows
gem "wdm", ">= 0.1.0" if Gem.win_platform?

# Lock http_parser.rb gem to v0.6.x on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]